"""
Django settings for educacion_continua project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fws#87b7noy=@a^(s(%m*oa_m2an$=2&5_7fvnk4gwf5!s=y&)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


AUTH_USER_MODEL = 'seguridad.Usuario'
"""
  """

# Application definition

INSTALLED_APPS = [
    #SEGURIDAD
    'seguridad',
    'rest_auth',
    'rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rolepermissions',
    'corsheaders',
    #-----------------
    'django.contrib.sites',
    'django.contrib.humanize',
    'django_cleanup',
    'dal',
    'dal_select2',
    'dal_queryset_sequence',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'fontawesome_5',
    'bootstrap4',
    'multiselectfield',
    'djmoney',
    'rest_framework',
    'rest_framework.authtoken',
    #ADMINISTRATIVO
    'administrativo.proveedores',
    'administrativo.productos',
    'administrativo.calificacion_proveedores',
    'administrativo.suministros',
    'administrativo.suministros_egreso',
    'administrativo.ingreso_bienes',
    'administrativo.consulta_bienes',
    'administrativo.solicitudes_compra',
    'administrativo.ordenes_compra',
    'administrativo.analisis_cotizaciones',
    'administrativo.mantenimientos',
    'administrativo.inventarios',
    #VENTAS
    'ventas',
    'ventas.reporte_contacto',
    'ventas.personas_juridicas',
    'ventas.personas_naturales',
    'ventas.propuesta_corp',
    'ventas.proformas',
    'ventas.interesados',
    'ventas.seguimientos',
    #FINANCIERO
    'financiero',
    'financiero.perfiles',
    'financiero.orden_facturacion',
    'financiero.orden_ingreso',
    "financiero.presupuestos",
    "financiero.orden_pago",
    "financiero.pago_eventos",
    "financiero.presupuestos_anuales",
    "financiero.plan_anual_compras",
    "financiero.procesos_especiales",
    #ACADEMICO
    'academico.evento',
    'academico.diseño_evento',
    'academico.plan_trabajo',
    'academico.docente',
    'academico.participante',
    'ckeditor',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'filters',
    'django_filters',
]

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
)

ROLEPERMISSIONS_MODULE = 'seguridad.roles'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER= 'appradiosoftware@gmail.com'
EMAIL_HOST_PASSWORD= 'educontinua'

ALLOWED_HOSTS = ['157.230.227.213']

CORS_ORIGIN_ALLOW_ALL = True
'''
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8100",
    "http://127.0.0.1:8100"
]
'''
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'

]

ROOT_URLCONF = 'educacion_continua.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SITE_ID = 1

WSGI_APPLICATION = 'educacion_continua.wsgi.application'

LOGIN_URL='/login/?next=/'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'edu_continuadb',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework.authentication.TokenAuthentication',
)
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DECIMAL_SEPARATOR = "."

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "staticfiles"),
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT=os.path.join(BASE_DIR, "static")
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/archivos/'

DATE_FORMAT= "d/m/Y"

CRISPY_TEMPLATE_PACK = 'bootstrap4'

CKEDITOR_CONFIGS = {
    'default':{
        'toolbar':'Custom',
        'toolbar_Custom':[
            ['Format', 'Font', 'FontSize'],
            ['Bold','Italic','Underline'],
            ['NumberedList','BulletedList','-','Outdent','Indent','-',
            'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Table']
        ],
        'height': '150px',
        'width': '100%',
    }
}