from rolepermissions.roles import AbstractUserRole

class Administrador(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': True,
        'vista_administrativo': True,
        'vista_ventas': True,
        'vista_encuestas': True,
        'agregar_academico': True,
        'editaraprobar_academico': True,
        'consultar_academico': True,
        'agregar_financiero': True,
        'editaraprobar_financiero': True,
        'consultar_financiero': True,
        'agregar_administrativo': True,
        'editaraprobar_administrativo': True,
        'consultar_administrativo': True,
        'agregar_ventas': True,
        'editaraprobar_ventas': True,
        'consultar_ventas': True,
        'agregar_encuestas': True,
        'editaraprobar_encuestas': True,
        'consultar_encuestas': True,
        'seguridad': True,
        'docentes': True,
    }

class Docente(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': True,
    }

class Observadorgeneral(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': True,
        'vista_administrativo': True,
        'vista_ventas': True,
        'vista_encuestas': True,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': True,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': True,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': True,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': True,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': True,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadorgeneral(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': True,
        'vista_administrativo': True,
        'vista_ventas': True,
        'vista_encuestas': True,
        'agregar_academico': False,
        'editaraprobar_academico': True,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': True,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': True,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': True,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': True,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistageneral(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': True,
        'vista_administrativo': True,
        'vista_ventas': True,
        'vista_encuestas': True,
        'agregar_academico': True,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': True,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': True,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': True,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': True,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Observadoracademico(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': True,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadoracademico(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': True,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistaacademico(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': True,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': True,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Observadorfinanciero(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': True,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': True,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadorfinanciero(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': True,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': True,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistafinanciero(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': True,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': True,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Observadoradministrativo(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': True,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': True,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadoradministrativo(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': True,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': True,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistaadministrativo(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': True,
        'vista_ventas': False,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': True,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Observadorcomercial(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': True,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': True,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadorcomercial(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': True,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': True,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistacomercial(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': True,
        'vista_encuestas': False,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': True,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Observadorencuestas(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': True,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': True,
        'seguridad': False,
        'docentes': False,
    }

class Coordinadorencuestas(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': True,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': False,
        'editaraprobar_encuestas': True,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }

class Analistaencuestas(AbstractUserRole):
    available_permissions = {
        'home': True,
        'edit_password': True,
        'vista_academico': False,
        'vista_financiero': False,
        'vista_administrativo': False,
        'vista_ventas': False,
        'vista_encuestas': True,
        'agregar_academico': False,
        'editaraprobar_academico': False,
        'consultar_academico': False,
        'agregar_financiero': False,
        'editaraprobar_financiero': False,
        'consultar_financiero': False,
        'agregar_administrativo': False,
        'editaraprobar_administrativo': False,
        'consultar_administrativo': False,
        'agregar_ventas': False,
        'editaraprobar_ventas': False,
        'consultar_ventas': False,
        'agregar_encuestas': True,
        'editaraprobar_encuestas': False,
        'consultar_encuestas': False,
        'seguridad': False,
        'docentes': False,
    }